DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS fields;
DROP TABLE IF EXISTS records;
DROP TABLE IF EXISTS images;

CREATE TABLE users
(
    userId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE
    first VARCHAR(255) NOT NULL,
    last VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    records INTEGER DEFAULT 0,
    PRIMARY KEY ( userId )
);

CREATE TABLE projects
(
    projectId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL UNIQUE,
    fieldsPerImage INTEGER NOT NULL,
    firstYCoord INTEGER NOT NULL,
    recordHeight INTEGER NOT NULL,
    PRIMARY KEY ( projectId ) 
);

CREATE TABLE fields
(
    fieldId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL,
    xCoord INTEGER NOT NULL,
    width INTEGER NOT NULL,
    helpHtml VARCHAR(255) NOT NULL,
    col INTEGER NOT NULL,
    refProjectId INTEGER NOT NULL,
    PRIMARY KEY ( fieldId )
);

CREATE TABLE records
(
    refImageId INTEGER NOT NULL PRIMARY KEY,
    refFieldId INTEGER NOT NULL PRIMARY KEY,
    rowNumber INTEGER NOT NULL PRIMARY KEY,
    value VARCHAR(255),
);

CREATE TABLE images
(
    imageId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    filePath VARCHAR(255) NOT NULL,
    imageTitle VARCHAR(255) NOT NULL,
    refProjectId INTEGER NOT NULL,
    currentUser INTEGER,
    PRIMARY KEY ( imageId )
);

